# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - MATHINK-AUTH-server

on:
  push:
    branches:
      - AUTH
  workflow_dispatch:

env:
  NOTEAPI_URL: ${{ secrets.NOTEAPI_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PASSWD: ${{ secrets.DB_PASSWD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1F99ED3A1474911B583614B2299DEE5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_535C200AD0DE48C0AFABFBD397AE56ED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2FAD70291EE5471AB06FE81BAE37A285 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MATHINK-AUTH-server'
          slot-name: 'Production'
          package: 'AUTH-0.0.1-SNAPSHOT.jar'
          