# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - OCR-server

on:
  push:
    branches:
      - OCR
  workflow_dispatch:

env:
  AUTH_URL: ${{ secrets.AUTH_URL }}
  MATHPIX_APP_ID: ${{ secrets.MATHPIX_APP_ID }}
  MATHPIX_APP_KEY: ${{ secrets.MATHPIX_APP_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A5B85613908A49A3A8B68756A3F78349 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_62342E02A17547E29D26090B93796D64 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E3A87AB4A2F4D60AA30FA77721AC10E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OCR-server'
          slot-name: 'Production'
          package: 'OCR-0.0.1-SNAPSHOT.jar'
          